In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

# Load iris dataset from sklearn
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add species column
df['species'] = [iris.target_names[i] for i in iris.target]

In [ ]:
# Display first 5 rows
print("First 5 Rows:\n")
df.head()

First 5 Rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [ ]:
print("\n\nSUMMARY STATISTICS GROUPED BY SPECIES\n")
# categorial value = species, quantatative variables = sepal and petal len,width
summary = df.groupby('species').agg(
    ['mean', 'median', 'min', 'max', 'std']
).round(2)

summary

SUMMARY STATISTICS GROUPED BY SPECIES

           sepal length (cm)                        sepal width (cm)         \
                        mean median  min  max   std             mean median
species
setosa                  5.01    5.0  4.3  5.8  0.35             3.43    3.4
versicolor              5.94    5.9  4.9  7.0  0.52             2.77    2.8
virginica               6.59    6.5  4.9  7.9  0.64             2.97    3.0

                           petal length (cm)                         \
            min  max   std              mean median  min  max   std
species
setosa      2.3  4.4  0.38              1.46   1.50  1.0  1.9  0.17
versicolor  2.0  3.4  0.31              4.26   4.35  3.0  5.1  0.47
virginica   2.2  3.8  0.32              5.55   5.55  4.5  6.9  0.55

           petal width (cm)
                       mean median  min  max   std
species
setosa                 0.25    0.2  0.1  0.6  0.11
versicolor             1.33    1.3  1.0  1.8  0.20
virginica              2.03    2.0  1.4  2.5  0.27

In [ ]:
# 2 Statistical Details For Each Species
species_list = df['species'].unique()

for species in species_list:

    print("\n===================================")
    print("Species :", species)
    print("===================================")

    # Filter rows of one species
    data = df[df['species'] == species]

    # Basic statistical details
    print("\nBasic Statistics:\n")
    display(data.describe().round(2))

    # Percentiles
    print("\nPercentiles:\n")
    display(
        data.quantile(
            [0.25, 0.50, 0.75],
            numeric_only=True
        ).round(2)
    )

===================================
Species : setosa
===================================

Basic Statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,50.00,50.00,50.00,50.00
mean,5.01,3.43,1.46,0.25
std,0.35,0.38,0.17,0.11
min,4.30,2.30,1.00,0.10
25%,4.80,3.20,1.40,0.20
50%,5.00,3.40,1.50,0.20
75%,5.20,3.68,1.58,0.30
max,5.80,4.40,1.90,0.60

Percentiles:

      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0.25                4.8              3.20               1.40               0.2
0.50                5.0              3.40               1.50               0.2
0.75                5.2              3.68               1.58               0.3

===================================
Species : versicolor
===================================

Basic Statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,50.00,50.00,50.00,50.00
mean,5.94,2.77,4.26,1.33
std,0.52,0.31,0.47,0.20
min,4.90,2.00,3.00,1.00
25%,5.60,2.52,4.00,1.20
50%,5.90,2.80,4.35,1.30
75%,6.30,3.00,4.60,1.50
max,7.00,3.40,5.10,1.80

Percentiles:

      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0.25                5.6              2.52               4.00               1.2
0.50                5.9              2.80               4.35               1.3
0.75                6.3              3.00               4.60               1.5

===================================
Species : virginica
===================================

Basic Statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,50.00,50.00,50.00,50.00
mean,6.59,2.97,5.55,2.03
std,0.64,0.32,0.55,0.27
min,4.90,2.20,4.50,1.40
25%,6.22,2.80,5.10,1.80
50%,6.50,3.00,5.55,2.00
75%,6.90,3.18,5.88,2.30
max,7.90,3.80,6.90,2.50

Percentiles:

      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0.25               6.22              2.80               5.10               1.8
0.50               6.50              3.00               5.55               2.0
0.75               6.90              3.18               5.88               2.3

In [ ]:
print(dir(iris))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']

In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']